/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmfSlStencil {
        "numbers": number[];
    }
}
declare global {
    interface HTMLAmfSlStencilElement extends Components.AmfSlStencil, HTMLStencilElement {
    }
    var HTMLAmfSlStencilElement: {
        prototype: HTMLAmfSlStencilElement;
        new (): HTMLAmfSlStencilElement;
    };
    interface HTMLElementTagNameMap {
        "amf-sl-stencil": HTMLAmfSlStencilElement;
    }
}
declare namespace LocalJSX {
    interface AmfSlStencil {
        "numbers"?: number[];
        "onTotalChanged"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "amf-sl-stencil": AmfSlStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "amf-sl-stencil": LocalJSX.AmfSlStencil & JSXBase.HTMLAttributes<HTMLAmfSlStencilElement>;
        }
    }
}
